### ISSUE TITLE
increase tdoa precision

### ISSUE THREAD

**Issue by mihaifireball** [hcab14/TDoA#6]
it is possible to increase the TDoA precision in order to locate a transmission inside a city? (using at least 3 receivers within that city)
Thank you! :)

**Comment by hcab14** [comment]
Probably not: 1 sample @12 kHz corresponds to 25 km; the locations of the KiwiSDRs are sometimes not accurately set by users; etc... 

If you have IQ recordings I would be interested to have a look and see what can be done.

**Comment by hcab14** [comment]
Closing this issue for now. Feel free to re-open it.
